class EndPoint:
    login = '/rest/login'
    templates = '/rest/getTemplatesForChats'
    important_answers = '/rest/report/getImportantAnswers'
    reporter_statuses = '/rest/reporter/statuses'
    new_incident_card = '/rest/incident/getbyid'
    gos_service = '/rest/gosservice/all'
    get_new_incident = '/rest/incident/getNewIncident/'
    save_address = '/rest/incident/saveAddress/'
    register_incident = '/rest/incident/registerIncident/'
    save_injured = '/rest/incident/saveInjured/'
    save_gos_services = '/rest/incident/saveGosServices/'
    create_chain_incident = '/rest/incident/createChainIncident/'
    create_work_shift_group = '/rest/workShiftGroup/create/'
    deactivate_work_shift_group = '/rest/workShiftGroup/deactivate/'
    edit_staff_shift_group = '/rest/emp/editStaffShiftGroup/'
